"""SuperCollider code templates for pattern generation."""

from __future__ import annotations


def sc_header(title: str, source_file: str) -> str:
    """Generate the .scd file header."""
    return f"""\
// {title}
// Generated by bp2sc from: {source_file}
// Bol Processor BP3 → SuperCollider Pattern transpiler
//
// Usage:
//   1. Boot the server: s.boot;
//   2. Execute this file: Ctrl+Enter (select all)
//   3. To stop: Cmd+. or Ctrl+.
//   4. Morph live: re-evaluate individual Pdef blocks

(
"""


def sc_footer() -> str:
    """Generate the .scd file footer."""
    return """\
)
"""


def sc_synthdef_default() -> str:
    """Generate a minimal SynthDef for testing."""
    return """\
// Default SynthDef for testing (replace with your own)
SynthDef(\\bp2sc_default, {
    |out=0, freq=440, amp=0.1, gate=1, pan=0|
    var sig, env;
    env = EnvGen.kr(Env.adsr(0.01, 0.1, 0.6, 0.3), gate, doneAction: 2);
    sig = SinOsc.ar(freq) + Pulse.ar(freq * 1.001, 0.3, 0.3);
    sig = LPF.ar(sig, freq * 4);
    Out.ar(out, Pan2.ar(sig * env * amp, pan));
}).add;

"""


def sc_tempo(bpm: float) -> str:
    """Generate tempo setting."""
    return f"TempoClock.default.tempo = {bpm} / 60;\n"


def sc_pdef(name: str, body: str) -> str:
    """Wrap a pattern in Pdef.

    Note: Pdef expects a Pattern, not a bare Rest(). If the body is just Rest(),
    we replace it with Event.silent(0) which is a valid no-op pattern.
    """
    # Fix bare Rest() - not valid as Pdef body (causes 'put' not understood)
    if body == "Rest()":
        body = "Event.silent(0)"
    return f"Pdef(\\{_sc_name(name)},\n{_indent(body)}\n);\n"


def sc_pbind(pairs: list[tuple[str, str]]) -> str:
    """Generate a Pbind with key-value pairs."""
    items = []
    for key, val in pairs:
        items.append(f"\\{key}, {val}")
    inner = ",\n".join(items)
    return f"Pbind(\n{_indent(inner)}\n)"


def sc_pseq(elements: list[str], repeats: str = "1") -> str:
    """Generate a Pseq."""
    if len(elements) <= 4:
        inner = ", ".join(elements)
        return f"Pseq([{inner}], {repeats})"
    inner = ",\n".join(elements)
    return f"Pseq([\n{_indent(inner)}\n], {repeats})"


def sc_ppar(patterns: list[str]) -> str:
    """Generate a Ppar."""
    inner = ",\n".join(patterns)
    return f"Ppar([\n{_indent(inner)}\n])"


def sc_prand(elements: list[str], repeats: str = "1") -> str:
    """Generate a Prand."""
    inner = ", ".join(elements)
    return f"Prand([{inner}], {repeats})"


def sc_pseed(seed: int, pattern: str) -> str:
    """Wrap a pattern in Pseed for deterministic randomness."""
    return f"Pseed({seed}, {pattern})"


def sc_pfindur(duration: float, pattern: str) -> str:
    """Wrap a pattern in Pfindur to limit total duration (anti-timeout)."""
    return f"Pfindur({duration}, {pattern})"


def sc_pwrand(elements: list[str], weights: list[str], repeats: str = "1") -> str:
    """Generate a Pwrand with explicit weights."""
    el_str = ", ".join(elements)
    wt_str = ", ".join(weights)
    return f"Pwrand([{el_str}], [{wt_str}].normalizeSum, {repeats})"


def sc_pn(pattern: str, repeats: str = "2") -> str:
    """Generate a Pn (repeat wrapper)."""
    return f"Pn({pattern}, {repeats})"


def sc_rest() -> str:
    """Generate a Rest."""
    return "Rest()"


def sc_comment(text: str) -> str:
    """Generate a SC comment."""
    return f"// {text}"


def sc_play(pdef_name: str) -> str:
    """Generate play command for a Pdef."""
    return f"Pdef(\\{_sc_name(pdef_name)}).play;"


def _sc_name(name: str) -> str:
    """Sanitize a name for SuperCollider symbol."""
    # Replace non-alphanumeric chars
    result = name.replace("'", "_p").replace('"', "_q").replace(" ", "_")
    # Ensure it starts with a letter
    if result and result[0].isdigit():
        result = "g" + result
    return result


def _indent(text: str, level: int = 1) -> str:
    """Indent text by N tab stops."""
    prefix = "\t" * level
    return "\n".join(prefix + line for line in text.split("\n"))
